<?php
/** @package SemedDb::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("AgendaSGPMap.php");

/**
 * AgendaSGPDAO provides object-oriented access to the agenda_sgp table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package SemedDb::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class AgendaSGPDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var date */
	public $Data;

	/** @var time */
	public $Horario;

	/** @var string */
	public $Publico;

	/** @var string */
	public $Evento;

	/** @var string */
	public $Equipe;

	/** @var string */
	public $Local;



}
?>